package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 16 11:03:40 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for SaleHeaderView1.
     * @return SaleHeaderView1
     */
    public ViewObjectImpl getSaleHeaderView1() {
        return (ViewObjectImpl) findViewObject("SaleHeaderView1");
    }

    /**
     * Container's getter for SaleDetailView1.
     * @return SaleDetailView1
     */
    public ViewObjectImpl getSaleDetailView1() {
        return (ViewObjectImpl) findViewObject("SaleDetailView1");
    }

    /**
     * Container's getter for PartyMasterView1.
     * @return PartyMasterView1
     */
    public ViewObjectImpl getPartyMasterView1() {
        return (ViewObjectImpl) findViewObject("PartyMasterView1");
    }

    /**
     * Container's getter for ItemMasterView1.
     * @return ItemMasterView1
     */
    public ViewObjectImpl getItemMasterView1() {
        return (ViewObjectImpl) findViewObject("ItemMasterView1");
    }

    /**
     * Container's getter for SaleHeaderSaleDetailVL1.
     * @return SaleHeaderSaleDetailVL1
     */
    public ViewLinkImpl getSaleHeaderSaleDetailVL1() {
        return (ViewLinkImpl) findViewLink("SaleHeaderSaleDetailVL1");
    }
}

